.TH ntpc 1 "2023-07-27" "ntpc" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
ntpc \- a Tiny NTP client
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBntpc\fP
.\" --------------------------------------------------------------------
.SH DESCRIPTION
the \fBntpc\fP client fetches time from a user specified ntp server and synchronizes system clock accordingly using
.BR rtc(4)
.\" --------------------------------------------------------------------
.SH OPTIONS
There are no command line options.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBntpc\fP is released under the BSD 3-Clause License. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.BR rtc(4),
.BR ntpd(8)

